### Get current user
Get  http://localhost:8080/api/users/current
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDExNzk3LCJleHAiOjE2MzY0MTUzOTd9.-vJqNW0ycIUs8rYu3LyGTWi_P2MuolMBF0qb3FErv3M

### Create new campaign
POST  http://localhost:8080/api/campaigns
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDExNzk3LCJleHAiOjE2MzY0MTUzOTd9.-vJqNW0ycIUs8rYu3LyGTWi_P2MuolMBF0qb3FErv3M

{
    "campaignName": "Another new campaign!"
}

### Get all campaigns associated with user
Get  http://localhost:8080/api/campaigns
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDExNzk3LCJleHAiOjE2MzY0MTUzOTd9.-vJqNW0ycIUs8rYu3LyGTWi_P2MuolMBF0qb3FErv3M

### Post new text to specific campaign
POST  http://localhost:8080/api/campaigns/5/add-text
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDExNzk3LCJleHAiOjE2MzY0MTUzOTd9.-vJqNW0ycIUs8rYu3LyGTWi_P2MuolMBF0qb3FErv3M

{
    "content": "Here's a text!",
    "sendDay": 0,
    "sendHour": 15,
    "sendMinute": 1
}

### Get all texts in a specific campaign
Get  http://localhost:8080/api/campaigns/1
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDExNzk3LCJleHAiOjE2MzY0MTUzOTd9.-vJqNW0ycIUs8rYu3LyGTWi_P2MuolMBF0qb3FErv3M

### Update name of existing campaign
PUT  http://localhost:8080/api/campaigns/3
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDExNzk3LCJleHAiOjE2MzY0MTUzOTd9.-vJqNW0ycIUs8rYu3LyGTWi_P2MuolMBF0qb3FErv3M

{
    "campaignName": "My UPDATED third campaign!"
}

### Delete campaign
DELETE http://localhost:8080/api/campaigns/2
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDExNzk3LCJleHAiOjE2MzY0MTUzOTd9.-vJqNW0ycIUs8rYu3LyGTWi_P2MuolMBF0qb3FErv3M

### Enroll contacts in campaign
POST  http://localhost:8080/api/campaigns/5/enroll
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDExNzk3LCJleHAiOjE2MzY0MTUzOTd9.-vJqNW0ycIUs8rYu3LyGTWi_P2MuolMBF0qb3FErv3M

{
    "contactsToEnroll": [
        {
            "contactId": 4, 
            "timeZone": "pacific"
        }
    ]
}