### Get current user
Get  http://localhost:8080/api/users/current
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDA2MTYyLCJleHAiOjE2MzY0MDk3NjJ9.oxpoSPR3zfJqLSbNW_z-C_rWxalYXIGeCykdTrxm9OE

### Create new campaign
POST  http://localhost:8080/api/campaigns
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDA2MTYyLCJleHAiOjE2MzY0MDk3NjJ9.oxpoSPR3zfJqLSbNW_z-C_rWxalYXIGeCykdTrxm9OE

{
    "campaignName": "Today's campaign!"
}

### Get all campaigns associated with user
Get  http://localhost:8080/api/campaigns
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDA2MTYyLCJleHAiOjE2MzY0MDk3NjJ9.oxpoSPR3zfJqLSbNW_z-C_rWxalYXIGeCykdTrxm9OE

### Post new text to specific campaign
POST  http://localhost:8080/api/campaigns/1/add-text
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDA2MTYyLCJleHAiOjE2MzY0MDk3NjJ9.oxpoSPR3zfJqLSbNW_z-C_rWxalYXIGeCykdTrxm9OE

{
    "content": "Here's a text!",
    "sendDay": 0,
    "sendHour": 14,
    "sendMinute": 16
}

### Get all texts in a specific campaign
Get  http://localhost:8080/api/campaigns/1
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDA2MTYyLCJleHAiOjE2MzY0MDk3NjJ9.oxpoSPR3zfJqLSbNW_z-C_rWxalYXIGeCykdTrxm9OE

### Update name of existing campaign
PUT  http://localhost:8080/api/campaigns/3
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDA2MTYyLCJleHAiOjE2MzY0MDk3NjJ9.oxpoSPR3zfJqLSbNW_z-C_rWxalYXIGeCykdTrxm9OE

{
    "campaignName": "My UPDATED third campaign!"
}

### Delete campaign
DELETE http://localhost:8080/api/campaigns/2
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDA2MTYyLCJleHAiOjE2MzY0MDk3NjJ9.oxpoSPR3zfJqLSbNW_z-C_rWxalYXIGeCykdTrxm9OE

### Enroll contacts in campaign
POST  http://localhost:8080/api/campaigns/1/enroll
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjM2NDA2MTYyLCJleHAiOjE2MzY0MDk3NjJ9.oxpoSPR3zfJqLSbNW_z-C_rWxalYXIGeCykdTrxm9OE

{
    "contactsToEnroll": [
        {
            "contactId": 4, 
            "timeZone": "pacific"
        }
    ]
}